---
format: 
  pdf:
    include-in-header:
      text: '\pagenumbering{gobble}'

editor: visual
---

\today

Dr. Paul Montagna, Dr. Linda Deegan, Editors-in-Chief\
Estuaries and Coasts

\vfill

Dear Dr. Montagna and Dr. Deegan,

\vspace{0.5cm}

Enclosed please find our manuscript, titled \`Hot and fresh: evidence of climate-related suboptimal conditions for seagrass in a large Gulf coast estuary', to be considered as an original article in Estuaries and Coasts.

The long-term recovery of Tampa Bay is a nationally recognized success story that demonstrates how the USEPA National Estuary Program is a valuable model for collaborative management.  Through large-scale reductions in external nutrient loading, seagrasses have recovered in the bay, reaching an all-time high in 2016.  Since that time, seagrasses have declined by nearly 1/3 and questions remain regarding the role of climate-related stressors in contributing to this decline.  We leverage multiple data sources to describe changing water temperature and salinity in the bay and relate these trends to the recent seagrass loss from 2016 to present. No such comprehensive assessment has previously been conducted for Tampa Bay and our results provide context for how climate stressors can confound existing management models, particularly related to nutrient management. 

This work has not been published elsewhere, nor is it under consideration for publication anywhere else. Each author has contributed substantially to this work. All authors have contributed to the writing and review of the original draft. Analysis was conducted by the first author, with interpretation of results supported by all other co-authors. All authors have approved the final draft and the submitted product was prepared according to instructions for authors provided on the journal's website.

We greatly appreciate the opportunity to publish this work in Estuaries and Coasts and are confident readers will consider it a valuable contribution. Please feel free to contact us directly should additional information be needed.
 
\vspace{0.5cm}

Regards,

Marcus W. Beck, Tampa Bay Estuary Program, St. Petersburg, Florida, USA, [mbeck@tbep.org](mailto:mbeck@tbep.org)

\vfill